### ISSUE TITLE
Excellent job adding the alt descriptions for each img element!

### ISSUE THREAD

**Issue by josephtkim** [JorgvanderSchaaf/Colmar-new#2]
It can be a great idea to add alt descriptions to img elements, because they act as descriptions and placeholder for the images. In addition, alt descriptions are also useful because they can add specific text for search engines to use when looking for matches.

**Comment by JorgvanderSchaaf** [comment]
I didn't realise the alt descriptions are also spidered by search engines. Good to know! thx!
